[paths]
input = D:\DRBWBM\MODEL\Tisa_0814\meteo_projections\restore4life\pr_ssp245_ec_earth3_veg.nc
output = D:\DRBWBM\MODEL\Tisa_0814\meteo_projections\restore4life\pr_monthly_EARTH_SSP245.csv
var = pr

[time]
; daily | monthly | yearly
out_freq = monthly
start = 2031-01-01
end = 2060-12-31
; mean | sum (used when resampling to monthly/yearly)
time_agg = sum
agg_order = space_then_time    
# space_then_time | time_then_space

[space]
; mean | sum (used for aggregated outputs)
space_agg = mean
area_weighted = true

[outputs]
; Toggle outputs on/off
per_cell_points = false
full_domain_agg = true
area_agg = false

[points]
; Used only if outputs.per_cell_points = true
; Comma-separated lists (same length)
lat = 
lon = 
name = 

[area]
; Optional bbox (leave empty to disable)
; Format: latmin,latmax,lonmin,lonmax
bbox = 

[mask]
; Optional mask NetCDF (leave path empty to disable)
path =
var =
; Use either equals OR threshold to select the cells with maskmap
equals =
threshold = 
