--
-- 02a-create-hydro-tables.sql
--
-- Surface-water vector layers: River Network + Water Bodies.
--
-- Kept in a SEPARATE file (not 02-create-tables.sql) because that file is
-- regenerated by docker/scripts/export-seed-data.sh (pg_dump --schema-only of
-- calib_stations + subbasins) and would clobber any additions. This file is
-- never regenerated. It sorts after 02-create-tables.sql and before the seeds
-- (04a/04b) in docker-entrypoint-initdb.d's alphabetical run order.
--
-- Data is seeded from HydroRIVERS v1.0 and HydroLAKES v1.0 (clipped to the
-- Danube basin) by 04a-seed-rivers.sql.gz / 04b-seed-water-bodies.sql.gz, and
-- indexed in 06-create-indexes.sql. See HYDRO_DATA.md for sources, licenses,
-- and how to regenerate the seed data (docker/scripts/prepare-hydro-data.sh).
--
-- These are NOT TypeORM entities (queried only via raw SQL in TilesService),
-- so synchronize:true leaves them untouched.
--

SET client_min_messages = warning;

--
-- Name: rivers; Type: TABLE; Schema: public; Owner: -
-- Source: HydroRIVERS v1.0, full Danube network (all Strahler orders),
-- clipped to the Danube basin. Visible detail is tiered by zoom in
-- TilesService.riversMinOrderForZoom (smaller rivers appear when zoomed in).
--

CREATE TABLE IF NOT EXISTS public.rivers (
    id integer NOT NULL,
    -- MultiLineString (not LineString): clipping reaches at the basin boundary
    -- can split a single reach into several segments, and ogr2ogr loads them
    -- with -nlt PROMOTE_TO_MULTI so every row is uniformly multi.
    geom public.geometry(MultiLineString,4326),
    hyriv_id bigint,             -- HydroRIVERS unique reach id (HYRIV_ID)
    next_down bigint,            -- HYRIV_ID of the downstream reach (NEXT_DOWN)
    ord_stra integer,            -- Strahler stream order -> drives line width
    ord_flow integer,            -- logarithmic discharge size class (3..10)
    dis_av_cms double precision, -- long-term average discharge, m3/s (DIS_AV_CMS)
    length_km double precision   -- reach length, km (LENGTH_KM)
);

CREATE SEQUENCE IF NOT EXISTS public.rivers_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.rivers_id_seq OWNED BY public.rivers.id;
ALTER TABLE ONLY public.rivers ALTER COLUMN id SET DEFAULT nextval('public.rivers_id_seq'::regclass);

DO $$ BEGIN
    ALTER TABLE ONLY public.rivers ADD CONSTRAINT rivers_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR invalid_table_definition THEN NULL;
END $$;

--
-- Name: water_bodies; Type: TABLE; Schema: public; Owner: -
-- Source: HydroLAKES v1.0 (CC-BY 4.0), clipped to the Danube basin.
--

CREATE TABLE IF NOT EXISTS public.water_bodies (
    id integer NOT NULL,
    geom public.geometry(MultiPolygon,4326),
    hylak_id bigint,             -- HydroLAKES unique lake id (Hylak_id)
    lake_name character varying, -- lake name where known (Lake_name)
    lake_type integer,           -- 1=lake, 2=reservoir, 3=regulated (Lake_type)
    lake_area double precision,  -- surface area, km2 (Lake_area)
    depth_avg double precision,  -- average depth, m (Depth_avg)
    vol_total double precision,  -- total volume, mcm (Vol_total)
    shore_len double precision   -- shoreline length, km (Shore_len)
);

CREATE SEQUENCE IF NOT EXISTS public.water_bodies_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.water_bodies_id_seq OWNED BY public.water_bodies.id;
ALTER TABLE ONLY public.water_bodies ALTER COLUMN id SET DEFAULT nextval('public.water_bodies_id_seq'::regclass);

DO $$ BEGIN
    ALTER TABLE ONLY public.water_bodies ADD CONSTRAINT water_bodies_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR invalid_table_definition THEN NULL;
END $$;
